logging:
  level:
    org:
      springframework : INFO
server:
  port: 8888
spring:
  application:
    name: configserver
  devtools:
    add-properties: false
  cloud:
    config:
      server:
        git:
          uri: git@github.com:himorithm/configuration.git
          cloneOnStart: true
          ignoreLocalSshSettings: true
          timeout: 5
          strictHostKeyChecking: false
          force-pull: true
          deleteUntrackedBranches: true
          basedir: D:\config_data
          searchPaths: '{application}_{profile}'
          privateKey: |
                       -----BEGIN RSA PRIVATE KEY-----
                       MIIEogIBAAKCAQEA62g4mvh3XFWxgtm/quNdhHDjWsNixIRgz9JkAPRyxUCzNlRc
                       UW+j4zzuyc8J5y8xiIK4FdrF8lELNKI99vXhQx6jSwlVTwDKZ3LRzkr2Cw8n2+h6
                       S+PTJkSQ659h4OOI/vj7WE/2VFBcT1HSZljlqji3+gO3W2Ht+pGApyZjDp+ATTpi
                       CMk07dHTPum0ZU9WulMu9deeBC90ktq/fwV2izHzZB08Qs9Z08n3dYF77vkvBHB2
                       bk8yULZljZyGJ2WIdaJqhlSBgYd2AUmen8bDZ2itSKCFN2c80Ib57KCcX5scneOI
                       kXUzwODi34TLGZwJ6vmgZYk/UY3J2Bh/ZN3XlwIBJQKCAQB44n3utvEvakZlycNJ
                       6mB0cVInsHD9IWIlh7bQDtMnBYx12EsVD9Cy9ca6qJZh9aPQeno0vHN8bs5nIuGM
                       p8azw5/2GYysB1MuNArfjkb+wpftd2FlPaPHiv5Pe1vGgq4iEScfgwHz8eo2kczo
                       ctbNCF55d4erd3o0j+gee375qt3cMXaaJD6KnoJFrzH+kDolTMRS0N3ezIWRYr7T
                       XmTzUy/US9RBKPZS626EQ/u8V1Y3H368x9sz04KxXA/QA9WIdf1bbb5AESa0FrT3
                       Ix3Wn/mMqX7kuC+4fXOraZZsgEBofRThw0BqACA/LCStLjg5YrHh5bW6nrilJ4U5
                       GsF9AoGBAP0e81cdtmqWGTvSW2vi21Ek1eNHXpM+JwI1GhpdMx9vTY9LwpTabd8p
                       txwbLYX5xKrWJAsH23u3mxgYz+XjANCgnlyh5C5kzW31KIJNL+jXV2XQgvNeYYl9
                       fEyh6JfYISyWVW7dBxEZwWLOA6Mo5PesmEuMqmlx5Jv1w7m8HR8/AoGBAO4VsNMd
                       N/+1kWPXYYjWF8o/YRC8W5Ca5fT/Q7hC1ya7T96IaKvBEbXtprNLSNXXRxIuvj6z
                       dUGf+K1D1fq8yQqH6GPhjSP+R8omsYYFiF0WiOg9xgaHaSB/+225jBV+SkoumoVA
                       J82izmmxbo+s8UZwUEtJYt/FFcZP32PotQmpAoGAdEx9pJEcdilJ3TcjFeTFodKn
                       dkNizgfMu9M1gbweaGOSVphuKLdi6f5o42Zu3LEHVWlO1KK+yiPtUELAYrRoKIEm
                       Ko+SWoFXd7XUV4s/hqghPJ4SpytdPyvRU6RWHEC1S9ZemriUi1EF03NpdHqStvxF
                       +TLK1oBv9KFZ7Y3IMPMCgYEAoN45NLLgpduLwAA6+5eTiKddQqjIPxyNidzokUHr
                       UYV7J6hGuT1DUWk5SLZTzsHj6bDhaKLE2VBpwS3VxRfGG99J/kxKm8d8nVhqHEjt
                       b1RqV7sJQq6FTU+ONWGxrahbtZUcTDJEaFk/XCvHPnvFnkvjOcnNL2l9alGkxvcu
                       NvUCgYEA3D4ozwhUK0Z6yf2AQ7fQ4+Ae5tX6a7bgY5Vvi0hwKYuM1npcFVMVsOZB
                       QGn0nqocO7ZfqpXcup+QnQTr1u+bULiJO/ugnIQkZiACa+3iYk4Ipn5hpxzqs5AC
                       ALnTD64h+R8Ik/oV8f1klmzNQGlOJO6fNTPuK2XPFjfubnKaYxU=
                       -----END RSA PRIVATE KEY-----




